CIRCT: lib/Dialect/MSFT/ExportQuartusTcl.cpp File Reference
ExportQuartusTcl.cpp File Reference
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/MSFT/DeviceDB.h"
#include "circt/Dialect/MSFT/ExportTcl.h"
#include "circt/Dialect/MSFT/MSFTAttributes.h"
#include "circt/Dialect/MSFT/MSFTOps.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Dialect/Seq/SeqOps.h"
#include "circt/Support/LLVM.h"
#include "mlir/IR/Builders.h"
#include "mlir/Translation.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/raw_ostream.h"
Functions
void emitInnerRefPart (TclOutputState &s, hw::InnerRefAttr innerRef)
void emitPath (TclOutputState &s, PlacementDB::PlacedInstance inst)
static void emit (TclOutputState &s, PlacementDB::PlacedInstance inst, PhysLocationAttr pla)
Emit tcl in the form of: "set_location_assignment MPDSP_X34_Y285_N0 -to $parent|fooInst|entityName".
static void emit (TclOutputState &s, PlacementDB::PlacedInstance inst, PhysicalRegionRefAttr regionRef)
Emit tcl in the form of: set_instance_assignment -name PLACE_REGION "X1 Y1 X20 Y20" -to $parent|a|b|c set_instance_assignment -name RESERVE_PLACE_REGION OFF -to $parent|a|b|c set_instance_assignment -name CORE_ONLY_PLACE_REGION ON -to $parent|a|b|c set_instance_assignment -name REGION_NAME test_region -to $parent|a|b|c.
Function Documentation
emit() [1/2]
static void emit (TclOutputState & s, PlacementDB::PlacedInstance inst, PhysicalRegionRefAttr regionRef) static
Emit tcl in the form of: set_instance_assignment -name PLACE_REGION "X1 Y1 X20 Y20" -to $parent|a|b|c set_instance_assignment -name RESERVE_PLACE_REGION OFF -to $parent|a|b|c set_instance_assignment -name CORE_ONLY_PLACE_REGION ON -to $parent|a|b|c set_instance_assignment -name REGION_NAME test_region -to $parent|a|b|c.
Definition at line 119 of file ExportQuartusTcl.cpp.
References emitPath().
emit() [2/2]
static void emit (TclOutputState & s, PlacementDB::PlacedInstance inst, PhysLocationAttr pla) static
Emit tcl in the form of: "set_location_assignment MPDSP_X34_Y285_N0 -to $parent|fooInst|entityName".
Definition at line 81 of file ExportQuartusTcl.cpp.
References emitPath().
emitInnerRefPart()
void emitInnerRefPart (TclOutputState & s, hw::InnerRefAttr innerRef)
Definition at line 51 of file ExportQuartusTcl.cpp.
Referenced by emitPath().
emitPath()
void emitPath (TclOutputState & s, PlacementDB::PlacedInstance inst)
Definition at line 60 of file ExportQuartusTcl.cpp.
References emitInnerRefPart().
Referenced by emit().