CIRCT: lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp File Reference
ModuleInliner.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/CHIRRTLDialect.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Support/LLVM.h"
#include "mlir/IR/BlockAndValueMapping.h"
Functions
static void rename (StringRef prefix, Operation *op)
If this operation or any child operation has a name, add the prefix to that operation's name.
static void cloneAndRename (StringRef prefix, OpBuilder &b, BlockAndValueMapping &mapper, Operation &op)
Clone an operation, mapping used values and results with the mapper, and apply the prefix to the name of the operation.
static SmallVector< Value > mapPortsToWires (StringRef prefix, OpBuilder &b, BlockAndValueMapping &mapper, FModuleOp target)
This function is used before inlining a module, to handle the conversion between module ports and instance results.
static void mapResultsToWires (BlockAndValueMapping &mapper, SmallVectorImpl< Value > &wires, InstanceOp instance)
This function is used after inlining a module, to handle the conversion between module ports and instance results.
Function Documentation
cloneAndRename()
static void cloneAndRename (StringRef prefix, OpBuilder & b, BlockAndValueMapping & mapper, Operation & op) static
Clone an operation, mapping used values and results with the mapper, and apply the prefix to the name of the operation.
This will clone to the insert point of the builder.
Definition at line 50 of file ModuleInliner.cpp.
References rename().
mapPortsToWires()
static SmallVector<Value> mapPortsToWires (StringRef prefix, OpBuilder & b, BlockAndValueMapping & mapper, FModuleOp target) static
This function is used before inlining a module, to handle the conversion between module ports and instance results.
For every port in the target module, create a wire, and assign a mapping from each module port to the wire. When the body of the module is cloned, the value of the wire will be used instead of the module's ports.
Definition at line 61 of file ModuleInliner.cpp.
mapResultsToWires()
static void mapResultsToWires (BlockAndValueMapping & mapper, SmallVectorImpl< Value > & wires, InstanceOp instance) static
This function is used after inlining a module, to handle the conversion between module ports and instance results.
This maps each wire to the result of the instance operation. When future operations are cloned from the current block, they will use the value of the wire instead of the instance results.
Definition at line 83 of file ModuleInliner.cpp.
rename()
static void rename (StringRef prefix, Operation * op) static
If this operation or any child operation has a name, add the prefix to that operation's name.
Definition at line 33 of file ModuleInliner.cpp.
References circt::calyx::direction::get().
Referenced by cloneAndRename().